import { z } from 'zod';
import { AIProvider } from './ai-provider.interface.js';
import { AIRequestOptions } from '../contracts/ai.contract.js';

export class MockAIProvider implements AIProvider {
  public readonly name: string = 'mock-ai-provider';
  private mockTextResponse?: string;
  private mockStructuredResponse?: unknown;
  private shouldFail: boolean = false;
  private failureError?: Error;

  constructor(options?: {
    mockTextResponse?: string;
    mockStructuredResponse?: unknown;
    shouldFail?: boolean;
    failureError?: Error;
  }) {
    if (options) {
      this.mockTextResponse = options.mockTextResponse;
      this.mockStructuredResponse = options.mockStructuredResponse;
      this.shouldFail = options.shouldFail ?? false;
      this.failureError = options.failureError;
    }
  }

  setMockTextResponse(response: string): void {
    this.mockTextResponse = response;
  }

  setMockStructuredResponse(response: unknown): void {
    this.mockStructuredResponse = response;
  }

  setFailure(shouldFail: boolean, error?: Error): void {
    this.shouldFail = shouldFail;
    this.failureError = error;
  }

  async generateText(prompt: string, _options?: AIRequestOptions): Promise<string> {
    if (this.shouldFail) {
      throw this.failureError || new Error('Mock AI provider simulated failure');
    }

    return this.mockTextResponse || `Mock completion response for prompt: "${prompt.slice(0, 30)}..."`;
  }

  async generateStructured<T>(_prompt: string, _schema: z.ZodType<T>, _options?: AIRequestOptions): Promise<unknown> {
    if (this.shouldFail) {
      throw this.failureError || new Error('Mock AI provider simulated failure');
    }

    if (this.mockStructuredResponse !== undefined) {
      return this.mockStructuredResponse;
    }

    // Default valid FieldLine field-progress extraction payload
    const defaultFieldProgressPayload = {
      items: [
        {
          reference: 'foundation work',
          location: 'Block B',
          progress_percent: 60,
          status: 'in_progress'
        }
      ]
    };

    if (_schema.safeParse(defaultFieldProgressPayload).success) {
      return defaultFieldProgressPayload;
    }

    // Default valid assistant grounded answer payload (Pass 18 Final Grounding Correction)
    const defaultAssistantAnswerPayload = {
      answer: 'Mock grounded assistant answer.',
      claims: [
        {
          type: 'metric',
          factRef: 'mock-ref',
          field: 'actualProgress',
          value: 60,
          text: 'Mock grounded assistant answer.'
        }
      ]
    };

    if (_schema.safeParse(defaultAssistantAnswerPayload).success) {
      return defaultAssistantAnswerPayload;
    }

    // Default valid assistant intent payload
    const defaultAssistantIntentPayload = {
      intent: 'delayed',
      activityQuery: null,
      explicitDate: null
    };

    if (_schema.safeParse(defaultAssistantIntentPayload).success) {
      return defaultAssistantIntentPayload;
    }

    // Default valid generic mock extraction contract
    return {
      summary: 'Mock extracted summary of field progress',
      confidenceScore: 0.95,
      entities: [
        { name: 'foundation_concrete', value: '75%', confidence: 0.92 }
      ],
      notes: 'Generated by deterministic MockAIProvider'
    };
  }
}
