import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { initDatabase, closeDatabase, getDatabase } from '../src/database/db.js';
import { SqliteProjectRepository } from '../src/repositories/project.repository.js';
import { SqliteScheduleRepository } from '../src/repositories/schedule.repository.js';
import { SqliteActivityRepository } from '../src/repositories/activity.repository.js';
import { SqliteProgressUpdateRepository } from '../src/repositories/progress-update.repository.js';
import { SqliteActivityMatchRepository } from '../src/repositories/activity-match.repository.js';
import { SqliteNotificationOutboxRepository } from '../src/repositories/notification-outbox.repository.js';
import { NotificationWorker } from '../src/services/anomaly/notification.worker.js';
import type { AnomalyAlertMessage, AnomalyMessageGeneratorService, GenerateAnomalyMessageInput } from '../src/services/anomaly/anomaly-message.types.js';
import type { EmailDeliveryResult, EmailDeliveryService } from '../src/services/anomaly/email/email-delivery.types.js';

describe('Phase 4 — NotificationWorker & Delivery Reliability', () => {
  let projectRepo: SqliteProjectRepository;
  let scheduleRepo: SqliteScheduleRepository;
  let activityRepo: SqliteActivityRepository;
  let progressUpdateRepo: SqliteProgressUpdateRepository;
  let activityMatchRepo: SqliteActivityMatchRepository;
  let outboxRepo: SqliteNotificationOutboxRepository;

  let testProjectId: string;
  let testScheduleId: string;
  let testActivityId: string;
  let testProgressUpdateId: string;
  let testMatchId: string;

  const sampleMessageInput: GenerateAnomalyMessageInput = {
    projectName: 'Pipeline Terminal Alpha',
    activityExternalId: 'ACT-PIPE-101',
    activityName: 'Fuel Gas Header Welding',
    activityLocation: 'Sector 4',
    reportDate: '2026-08-16',
    reporterName: 'Carlos Lead',
    previousPercent: 12,
    reportedPercent: 90,
    anomalyScore: 0.89,
    anomalySeverity: 'high',
    anomalyReasons: ['Daily increment exceeds shift variance threshold'],
    activityMatchId: 'match_worker_test'
  };

  const sampleAlertMessage: AnomalyAlertMessage = {
    title: 'High Velocity Deviation Flagged: Fuel Gas Header Welding',
    summary: 'Reported progress increased from 12% to 90% in one shift.',
    details: 'Field report submitted by Carlos Lead indicates unexpected completion velocity.',
    recommendedAction: 'Verify field inspection signoff and radiographic test logs.',
    fullMessage: 'Comprehensive anomaly explanation generated by Groq.',
    activityMatchId: 'match_worker_test',
    projectName: 'Pipeline Terminal Alpha',
    activityExternalId: 'ACT-PIPE-101',
    activityName: 'Fuel Gas Header Welding',
    activityLocation: 'Sector 4',
    reportDate: '2026-08-16',
    reporterName: 'Carlos Lead',
    previousPercent: 12,
    reportedPercent: 90,
    severity: 'high',
    anomalyScore: 0.89,
    anomalyReasons: ['Daily increment exceeds shift variance threshold'],
    generatedBy: 'groq',
    generatedAt: '2026-08-16T12:00:00.000Z'
  };

  beforeEach(() => {
    initDatabase({ dbPath: ':memory:' });
    const db = getDatabase();

    projectRepo = new SqliteProjectRepository(() => db);
    scheduleRepo = new SqliteScheduleRepository(() => db);
    activityRepo = new SqliteActivityRepository(() => db);
    progressUpdateRepo = new SqliteProgressUpdateRepository(() => db);
    activityMatchRepo = new SqliteActivityMatchRepository(() => db);
    outboxRepo = new SqliteNotificationOutboxRepository(() => db);

    const proj = projectRepo.create({
      code: 'PIPE-TERM',
      name: 'Pipeline Terminal Alpha'
    });
    testProjectId = proj.id;

    const sched = scheduleRepo.create({
      projectId: testProjectId,
      name: 'Alpha Schedule',
      sourceType: 'manual',
      isBaseline: true
    });
    testScheduleId = sched.id;

    const act = activityRepo.create({
      projectId: testProjectId,
      scheduleId: testScheduleId,
      externalId: 'ACT-PIPE-101',
      name: 'Fuel Gas Header Welding',
      plannedStart: '2026-08-01',
      plannedFinish: '2026-08-30',
      baselineProgress: 0
    });
    testActivityId = act.id;

    const pu = progressUpdateRepo.create({
      projectId: testProjectId,
      reportDate: '2026-08-16',
      rawText: 'Welding reached 90%',
      sourceType: 'manual',
      status: 'received'
    });
    testProgressUpdateId = pu.id;

    const match = activityMatchRepo.create({
      projectId: testProjectId,
      progressUpdateId: testProgressUpdateId,
      activityId: testActivityId,
      confidenceScore: 1.0,
      matchMethod: 'exact_id',
      status: 'confirmed',
      anomalyScore: 0.89,
      anomalySeverity: 'high'
    });
    testMatchId = match.id;
  });

  afterEach(() => {
    closeDatabase();
  });

  describe('Success Lifecycle & Message ID Capture', () => {
    it('1. Delivers notification, records provider_message_id, sets delivered_at, and saves message snapshot', async () => {
      let groqCalls = 0;
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockImplementation(async () => {
          groqCalls++;
          return { ...sampleAlertMessage, activityMatchId: testMatchId };
        })
      };

      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockResolvedValue({
          sent: true,
          provider: 'resend',
          providerMessageId: 'resend_msg_success_999'
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // Claim & process
      const processed = await worker.processNextNotification();
      expect(processed).toBe(true);

      const refreshed = outboxRepo.getById(outboxItem.id);
      expect(refreshed?.status).toBe('delivered');
      expect(refreshed?.deliveredAt).toBeDefined();
      expect(refreshed?.providerMessageId).toBe('resend_msg_success_999');
      expect(refreshed?.attemptCount).toBe(1);
      expect(refreshed?.lockedAt).toBeNull();

      // Verify Groq was invoked exactly once
      expect(groqCalls).toBe(1);

      // Verify payload_json now holds the immutable message snapshot
      const payload = JSON.parse(refreshed!.payloadJson);
      expect(payload.message).toBeDefined();
      expect(payload.message.title).toBe(sampleAlertMessage.title);
    });
  });

  describe('Retry Classification & Bounded Backoff', () => {
    it('2. Retryable Failures: 429, 503, and TIMEOUT transition to retry_wait with increasing next_attempt_at', async () => {
      const customDelaysMs = [1000, 2000, 4000]; // 1s, 2s, 4s for test

      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockResolvedValue({ ...sampleAlertMessage, activityMatchId: testMatchId })
      };

      let deliveryAttempt = 0;
      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockImplementation(async () => {
          deliveryAttempt++;
          if (deliveryAttempt === 1) {
            return { sent: false, provider: 'resend', errorCode: 'RATE_LIMIT', errorSummary: 'HTTP 429' };
          }
          if (deliveryAttempt === 2) {
            return { sent: false, provider: 'resend', errorCode: 'SERVER_ERROR', errorSummary: 'HTTP 503' };
          }
          return { sent: false, provider: 'resend', errorCode: 'TIMEOUT', errorSummary: 'Gateway Timeout' };
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery,
        backoffDelaysMs: customDelaysMs
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // Attempt 1: 429
      const startTime = Date.now();
      await worker.processNextNotification();
      let row = outboxRepo.getById(outboxItem.id)!;
      expect(row.status).toBe('retry_wait');
      expect(row.attemptCount).toBe(1);
      expect(row.lastErrorCode).toBe('RATE_LIMIT');
      const delay1 = new Date(row.nextAttemptAt!).getTime() - startTime;
      expect(delay1).toBeGreaterThanOrEqual(900);
      expect(delay1).toBeLessThanOrEqual(1500);

      // Attempt 2: 503
      // Fast forward time to allow second claim
      const tAfter1 = new Date(Date.now() + 2000).toISOString();
      const claimed2 = outboxRepo.claimNextEligible(tAfter1)!;
      await worker.processNotification(claimed2);
      row = outboxRepo.getById(outboxItem.id)!;
      expect(row.status).toBe('retry_wait');
      expect(row.attemptCount).toBe(2);
      expect(row.lastErrorCode).toBe('SERVER_ERROR');

      // Attempt 3: TIMEOUT
      const tAfter2 = new Date(Date.now() + 5000).toISOString();
      const claimed3 = outboxRepo.claimNextEligible(tAfter2)!;
      await worker.processNotification(claimed3);
      row = outboxRepo.getById(outboxItem.id)!;
      expect(row.status).toBe('retry_wait');
      expect(row.attemptCount).toBe(3);
      expect(row.lastErrorCode).toBe('TIMEOUT');
    });

    it('3. Permanent Failures: 400 and 401 transition immediately to failed without endless retries', async () => {
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockResolvedValue({ ...sampleAlertMessage, activityMatchId: testMatchId })
      };

      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockResolvedValue({
          sent: false,
          provider: 'resend',
          errorCode: 'AUTH_ERROR',
          errorSummary: 'HTTP 401 Invalid API Key'
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      await worker.processNextNotification();

      const refreshed = outboxRepo.getById(outboxItem.id);
      expect(refreshed?.status).toBe('failed');
      expect(refreshed?.lastErrorCode).toBe('AUTH_ERROR');
      expect(refreshed?.attemptCount).toBe(1);

      // Verified: worker cannot claim it anymore
      const nextClaim = outboxRepo.claimNextEligible();
      expect(nextClaim).toBeNull();
    });

    it('4. Maximum Attempts Limit: Transitions to failed when attemptCount reaches maxAttempts', async () => {
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockResolvedValue({ ...sampleAlertMessage, activityMatchId: testMatchId })
      };

      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockResolvedValue({
          sent: false,
          provider: 'resend',
          errorCode: 'RATE_LIMIT',
          errorSummary: 'HTTP 429'
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery,
        backoffDelaysMs: [10, 10, 10]
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        maxAttempts: 2,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // Attempt 1: 429 -> retry_wait
      await worker.processNextNotification();
      let row = outboxRepo.getById(outboxItem.id)!;
      expect(row.status).toBe('retry_wait');
      expect(row.attemptCount).toBe(1);

      // Attempt 2: 429 -> reaches maxAttempts (2) -> failed
      const claimed2 = outboxRepo.claimNextEligible(new Date(Date.now() + 1000).toISOString())!;
      await worker.processNotification(claimed2);
      row = outboxRepo.getById(outboxItem.id)!;
      expect(row.status).toBe('failed');
      expect(row.lastErrorCode).toBe('MAX_ATTEMPTS_EXCEEDED');
    });
  });

  describe('Message Stability & Groq Invariant', () => {
    it('5. Groq Call Count: Retries reuse the snapshotted payload and NEVER call Groq again', async () => {
      let groqCallCount = 0;
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockImplementation(async () => {
          groqCallCount++;
          return {
            ...sampleAlertMessage,
            title: `Generated Anomaly Alert #${groqCallCount}`,
            activityMatchId: testMatchId
          };
        })
      };

      let deliveryCalls = 0;
      let deliveredPayloads: AnomalyAlertMessage[] = [];

      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockImplementation(async (msg: AnomalyAlertMessage) => {
          deliveryCalls++;
          deliveredPayloads.push(msg);
          if (deliveryCalls === 1) {
            return { sent: false, provider: 'resend', errorCode: 'SERVER_ERROR', errorSummary: '503 Outage' };
          }
          return { sent: true, provider: 'resend', providerMessageId: 'resend_ok_retry' };
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery,
        backoffDelaysMs: [10]
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // First run: fails with 503
      await worker.processNextNotification();
      expect(groqCallCount).toBe(1);
      expect(deliveryCalls).toBe(1);

      // Second run: succeeds
      const claimed2 = outboxRepo.claimNextEligible(new Date(Date.now() + 1000).toISOString())!;
      await worker.processNotification(claimed2);

      // Critical Invariant: Groq was NOT called again on retry
      expect(groqCallCount).toBe(1);
      expect(deliveryCalls).toBe(2);

      // Both delivery attempts used the EXACT same message title and contents
      expect(deliveredPayloads[0].title).toBe('Generated Anomaly Alert #1');
      expect(deliveredPayloads[1].title).toBe('Generated Anomaly Alert #1');
    });
  });

  describe('Crash After Send & Idempotency Recovery', () => {
    it('6. Crash-After-Send: Stale recovery reuses identical Resend idempotency identity', async () => {
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockResolvedValue({ ...sampleAlertMessage, activityMatchId: testMatchId })
      };

      let sentCount = 0;
      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockImplementation(async () => {
          sentCount++;
          // First time: email accepted, but caller simulates process crash before DB update
          return { sent: true, provider: 'resend', providerMessageId: 'resend_msg_crash_demo' };
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        idempotencyKey: `fieldline-anomaly-alert:${testMatchId}`,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // Claim item 10 minutes ago
      const oldTime = new Date(Date.now() - 10 * 60 * 1000).toISOString();
      const claimed = outboxRepo.claimNextEligible(oldTime)!;

      // Simulate crash: Resend accepted email, but DB update never happened (row still says 'processing')
      expect(claimed.status).toBe('processing');

      // Process crash & reboot: Stale recovery detects expired lease (5 min lease timeout)
      const recoveredCount = worker.requeueStaleNotifications(5 * 60 * 1000);
      expect(recoveredCount).toBe(1);

      const requeuedRow = outboxRepo.getById(outboxItem.id)!;
      expect(requeuedRow.status).toBe('retry_wait');
      // Idempotency key MUST remain identical across crashes and retries
      expect(requeuedRow.idempotencyKey).toBe(`fieldline-anomaly-alert:${testMatchId}`);

      // Worker retries the notification
      const retryClaim = outboxRepo.claimNextEligible(new Date().toISOString())!;
      await worker.processNotification(retryClaim);

      const finalRow = outboxRepo.getById(outboxItem.id)!;
      expect(finalRow.status).toBe('delivered');
      expect(finalRow.providerMessageId).toBe('resend_msg_crash_demo');
      expect(finalRow.idempotencyKey).toBe(`fieldline-anomaly-alert:${testMatchId}`);
    });
  });

  describe('Anomaly Truth Failure Independence', () => {
    it('7. Resend failures NEVER alter or rollback the anomaly record', async () => {
      const mockGenerator: AnomalyMessageGeneratorService = {
        generateAnomalyMessage: vi.fn().mockResolvedValue({ ...sampleAlertMessage, activityMatchId: testMatchId })
      };

      // Resend repeatedly fails with 500 error
      const mockEmailDelivery: EmailDeliveryService = {
        sendAnomalyAlert: vi.fn().mockResolvedValue({
          sent: false,
          provider: 'resend',
          errorCode: 'SERVER_ERROR',
          errorSummary: 'Internal Server Error'
        })
      };

      const worker = new NotificationWorker({
        outboxRepo,
        messageGenerator: mockGenerator,
        emailDeliveryService: mockEmailDelivery,
        backoffDelaysMs: [10]
      });

      const outboxItem = outboxRepo.create({
        projectId: testProjectId,
        activityMatchId: testMatchId,
        maxAttempts: 1,
        payload: {
          messageInput: { ...sampleMessageInput, activityMatchId: testMatchId },
          message: null
        }
      });

      // Run to permanent failure
      await worker.processNextNotification();
      const finalOutbox = outboxRepo.getById(outboxItem.id);
      expect(finalOutbox?.status).toBe('failed');

      // Crucial Invariant: The anomaly match in SQLite is completely untouched
      const anomalyMatch = activityMatchRepo.getById(testMatchId);
      expect(anomalyMatch).not.toBeNull();
      expect(anomalyMatch?.anomalySeverity).toBe('high');
      expect(anomalyMatch?.anomalyScore).toBe(0.89);
      expect(anomalyMatch?.status).toBe('confirmed');
    });
  });
});
